on:
  push:
    branches: ["8-backup-recovery"]

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sprint branch
        uses: actions/checkout@v2
        with:
          ref: Sprint2

      - name: checkout backup
        run: |
          git fetch origin
          git branch -r
          git checkout -b backup origin/backup

      - name: fetch and rebase
        run: |
          git config --global user.email "ap2684@njit.edu"
          git config --global user.name "ap2684"
          git branch
          git fetch origin Sprint2
          git merge -X theirs origin/Sprint2 --allow-unrelated-histories

      - name: push backup
        run: git push origin backup --force-with-lease