name: Daily Backup

on:
#  schedule:
#    - cron: '*/5 * * * *'
  push:
    branches: ["8-backup-recovery"]

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Backup repository
        run: |
          git config --global user.name "ap2684"
          git config --global user.email "ap2684@njit.edu"
          git remote add project-2-team-sar https://github.com/ap2684/backup-project-2-team-sar.git
          git push --mirror https://github.com/ap2684/backup-project-2-team-sar.git
