name: Daily Backup

on:
  schedule:
    - cron: '*/5 * * * *' # Runs at 12:00am UTC every day

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Backup repository
        run: |
          git config --global user.name "ap2684"
          git config --global user.email "ap2684@njit.edu"
          pwd
          git config --list
          git clone https://github.com/NJIT-WIS/project-2-team-sar.git
          git remote add backup https://github.com/ap2684/backup-project-2-team-sar.git
          git push --mirror backup
