name: Daily Backup

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["8-backup-recovery"]
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sprint branch
      uses: actions/checkout@v2
      with:
        ref: Sprint2

    - name: Create backup branch
      #run: git branch backup || git checkout -b backup
      run: |
          if git rev-parse --verify backup >/dev/null 2>&1
          then
            echo "Backup branch already exists"
          else
            echo "Creating backup branch"
            git branch backup
          fi

    - name: Pull latest changes
      run: git pull origin Sprint2

    - name: Create backup branch from Sprint
      run: |
        if git rev-parse --verify backup >/dev/null 2>&1 
        then
          echo "Backup branch already exists, skipping."
        else
        echo "checkout backup branch"
          git checkout -b backup/Sprint2
        fi

    - name: Merge changes from Sprint
      run: git merge --no-commit Sprint2

    - name: Resolve conflicts
      run: git mergetool

    - name: Commit backup changes
      run: git commit -m "Backup of Sprint branch"

    - name: Push backup branch
      run: git push origin backup/Sprint2