name: Daily Backup

on:
  schedule:
    #- cron: '0 */12 * * *' # Backup every 12 hours
    - cron: '*/3 * * * *' # Backup every 12 hours

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sprint branch
      uses: actions/checkout@v2
      with:
        ref: 20-google-translate
    
    - name: Create backup branch
      #run: git branch backup || git checkout -b backup
      run: |
          if git rev-parse --verify backup >/dev/null 2>&1
          then
            echo "Backup branch already exists"
          else
            echo "Creating backup branch"
            git branch backup
          fi
    
    - name: Pull latest changes
      run: git pull origin 20-google-translate
      
    - name: Create backup branch from Sprint
      run: git checkout -b backup/20-google-translate
    
    - name: Merge changes from Sprint
      run: git merge --no-commit 20-google-translate
      
    - name: Resolve conflicts
      run: git mergetool
      
    - name: Commit backup changes
      run: git commit -m "Backup of Sprint branch"
      
    - name: Push backup branch
      run: git push origin backup/20-google-translate
