on:
  push:
    branches: ["8-backup-recovery"]

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sprint branch
        uses: actions/checkout@v2
        with:
          ref: Sprint2

      - name: checkout backup
        run: |
          git fetch origin
          git branch -r
          git checkout -b backup origin/backup

      - name: fetch and rebase
        run: |
          git fetch origin Sprint2
          git rebase origin/Sprint2

      - name: push backup
        run: git push origin backup --force-with-lease