name: Daily Backup

on:
  schedule:
    #- cron: '0 */12 * * *' # Backup every 12 hours
    - cron: '*/4 * * * *' # Backup every 12 hours

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check if backup branch exists
        run: |
          if git rev-parse --verify backup >/dev/null 2>&1
          then
            echo "Backup branch already exists"
          else
            echo "Creating backup branch"
            git branch backup
            git checkout backup
          fi
      - name: Pull changes from Sprint2 branch
        run: |
          git fetch origin Sprint2
          git merge origin/Sprint2
      - name: Push backup branch to remote
        run: |
          git pull origin backup --ff-only
          git push origin backup
