on:
  push:
    branches: ["8-backup-recovery"]

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sprint branch
        uses: actions/checkout@v2
        with:
          ref: Sprint2

      - name: Create backup branch
        run: git branch backup || git checkout -b backup

      - name: Pull latest changes
        run: git pull origin Sprint2

      - name: Create backup branch from Sprint
        run: |
          if git show-ref --verify --quiet "refs/heads/backup"; then
            if git show-ref --verify --quiet "refs/heads/backup/Sprint2"; then
              echo "here 1"
              git checkout backup/Sprint2
              echo "Backup branch already exists, skipping."
            else
              echo "here 2"
              git checkout backup/Sprint2
            fi
          else
            echo "here 3"
            git branch backup
            git checkout -b backup/Sprint2
          fi

      - name: Merge changes from Sprint
        run: git merge --no-commit Sprint2

      - name: Resolve conflicts
        run: git mergetool

      - name: Commit backup changes
        run: git commit -m "Backup of Sprint branch"

      - name: Push backup branch
        run: git push origin backup/Sprint2
